name: Build website

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build
    - name: Upload built website
      uses: actions/upload-artifact@v2.2.3
      with:
        # Artifact name
        name: website
        # A file, directory or wildcard pattern that describes what to upload
        path: publish/**/*
        if-no-files-found: error
        retention-days: 7
